name: "웹프로그래밍 실습 CI/CD"

on:
  push:
    branches:
      - main
    tags:
      - release.*

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "튜터링 때 만든 투두리스트... ${{ github.repository }}"
